name: g33k4u
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: g33k4u
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#251309'
    - '#6b371a'
    - '#934c29'
    - '#da7215'
    - '#c46530'
  brandStrength: 0.5
  lightness: 0.7485667476430535
  saturation: 0.6041226983070374
  rhythmicContrast: 0.12386293173767626
purpose: []
